# Generated by Django 4.2.7 on 2025-12-31 02:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('asset_type', models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software')], max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('IN_REPAIR', 'In Repair'), ('RETIRED', 'Retired'), ('DISPOSED', 'Disposed'), ('MISSING', 'Missing')], default='ACTIVE', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('end_of_life', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('UNASSIGNMENT', 'Unassignment'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asset Assignment',
                'verbose_name_plural': 'Asset Assignments',
                'db_table': 'asset_assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('STATUS_CHANGED', 'Status Changed'), ('TRANSFERRED', 'Transferred'), ('MAINTENANCE', 'Maintenance Record Added')], max_length=20)),
                ('description', models.TextField()),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Audit Log',
                'verbose_name_plural': 'Asset Audit Logs',
                'db_table': 'asset_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'db_table': 'asset_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive Maintenance'), ('CORRECTIVE', 'Corrective Maintenance'), ('UPGRADE', 'Upgrade'), ('REPAIR', 'Repair'), ('INSPECTION', 'Inspection')], max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Maintenance',
                'verbose_name_plural': 'Asset Maintenance Records',
                'db_table': 'asset_maintenance',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('ASSET_SUMMARY', 'Asset Summary'), ('ASSIGNMENT_REPORT', 'Assignment Report'), ('MAINTENANCE_REPORT', 'Maintenance Report'), ('WARRANTY_REPORT', 'Warranty Report'), ('COST_ANALYSIS', 'Cost Analysis'), ('DEPRECIATION_REPORT', 'Depreciation Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FilePathField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Asset Report',
                'verbose_name_plural': 'Asset Reports',
                'db_table': 'asset_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='HardwareAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('hardware_type', models.CharField(choices=[('COMPUTER', 'Desktop Computer'), ('LAPTOP', 'Laptop'), ('SERVER', 'Server'), ('MONITOR', 'Monitor'), ('PRINTER', 'Printer'), ('NETWORK_DEVICE', 'Network Device'), ('MOBILE_DEVICE', 'Mobile Device'), ('PERIPHERAL', 'Peripheral'), ('OTHER', 'Other')], max_length=20)),
                ('cpu', models.CharField(blank=True, max_length=100)),
                ('memory', models.CharField(blank=True, max_length=50)),
                ('storage', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hardware Asset',
                'verbose_name_plural': 'Hardware Assets',
                'db_table': 'hardware_assets',
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='SoftwareAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.asset')),
                ('software_type', models.CharField(choices=[('OPERATING_SYSTEM', 'Operating System'), ('PRODUCTIVITY', 'Productivity Suite'), ('DEVELOPMENT', 'Development Tool'), ('SECURITY', 'Security Software'), ('DATABASE', 'Database'), ('SERVER_SOFTWARE', 'Server Software'), ('MOBILE_APP', 'Mobile Application'), ('WEB_SERVICE', 'Web Service'), ('OTHER', 'Other')], max_length=20)),
                ('license_type', models.CharField(blank=True, choices=[('PERPETUAL', 'Perpetual License'), ('SUBSCRIPTION', 'Subscription'), ('FREEMIUM', 'Freemium'), ('OPEN_SOURCE', 'Open Source'), ('TRIAL', 'Trial')], max_length=20)),
                ('license_key', models.TextField(blank=True)),
                ('license_seats', models.PositiveIntegerField(default=1)),
                ('seats_used', models.PositiveIntegerField(default=0)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('support_end_date', models.DateField(blank=True, null=True)),
                ('download_url', models.URLField(blank=True)),
                ('installation_guide', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Software Asset',
                'verbose_name_plural': 'Software Assets',
                'db_table': 'software_assets',
            },
            bases=('assets.asset',),
        ),
    ]
