# Generated by Django 4.2.7 on 2026-01-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VIEWER', 'Viewer'), ('TECHNICIAN', 'Technician'), ('MANAGER', 'Manager'), ('IT_ADMIN', 'IT Administrator'), ('SUPERADMIN', 'Super Administrator')], default='VIEWER', max_length=20),
        ),
    ]
