# Generated by Django 4.2.7 on 2025-12-31 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload'), ('PRINT', 'Print'), ('SHARE', 'Share'), ('CHANGE_PASSWORD', 'Change Password'), ('RESET_PASSWORD', 'Reset Password'), ('PERMISSION_CHANGE', 'Permission Change'), ('CONFIGURATION_CHANGE', 'Configuration Change')], max_length=30)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=50)),
                ('resource_name', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('widgets', models.JSONField(default=list, help_text='Dashboard widget configurations')),
                ('layout', models.JSONField(default=dict, help_text='Dashboard layout configuration')),
                ('refresh_interval', models.PositiveIntegerField(default=300, help_text='Refresh interval in seconds')),
                ('is_public', models.BooleanField(default=False, help_text='Whether dashboard is publicly accessible')),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Successful Login'), ('LOGIN_FAILURE', 'Failed Login'), ('LOGOUT', 'User Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('SECURITY_VIOLATION', 'Security Violation'), ('DATA_BREACH_ATTEMPT', 'Data Breach Attempt'), ('XSS_ATTEMPT', 'XSS Attack Attempt'), ('SQL_INJECTION_ATTEMPT', 'SQL Injection Attempt'), ('CSRF_VIOLATION', 'CSRF Violation'), ('FILE_UPLOAD_BLOCKED', 'Blocked File Upload'), ('PERMISSION_DENIED', 'Permission Denied'), ('SESSION_EXPIRED', 'Session Expired'), ('TOKEN_EXPIRED', 'Token Expired'), ('SECURITY_CONFIG_CHANGE', 'Security Configuration Change')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('incident_type', models.CharField(choices=[('DATA_BREACH', 'Data Breach'), ('MALWARE_INFECTION', 'Malware Infection'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('DENIAL_OF_SERVICE', 'Denial of Service'), ('INSIDER_THREAT', 'Insider Threat'), ('PHISHING_ATTACK', 'Phishing Attack'), ('RANSOMWARE', 'Ransomware'), ('SYSTEM_COMPROMISE', 'System Compromise'), ('CONFIGURATION_ERROR', 'Configuration Error'), ('OTHER', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INVESTIGATING', 'Investigating'), ('CONTAINED', 'Contained'), ('ERADICATED', 'Eradicated'), ('RECOVERING', 'Recovering'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=15)),
                ('description', models.TextField()),
                ('impact_assessment', models.TextField(blank=True)),
                ('affected_systems', models.JSONField(blank=True, default=list)),
                ('affected_users', models.JSONField(blank=True, default=list)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contained_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_summary', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('preventive_measures', models.TextField(blank=True)),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('policy_type', models.CharField(choices=[('PASSWORD_POLICY', 'Password Policy'), ('ACCOUNT_LOCKOUT', 'Account Lockout Policy'), ('SESSION_POLICY', 'Session Policy'), ('RATE_LIMITING', 'Rate Limiting Policy'), ('ACCESS_CONTROL', 'Access Control Policy'), ('DATA_RETENTION', 'Data Retention Policy'), ('ENCRYPTION', 'Encryption Policy'), ('BACKUP_POLICY', 'Backup Policy'), ('INCIDENT_RESPONSE', 'Incident Response Policy')], max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft')], default='ACTIVE', max_length=10)),
                ('config', models.JSONField(default=dict, help_text='Policy-specific configuration')),
                ('rules', models.JSONField(default=list, help_text='List of policy rules')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('threshold_type', models.CharField(choices=[('FAILED_LOGIN_ATTEMPTS', 'Failed Login Attempts'), ('RATE_LIMIT_REQUESTS', 'Rate Limit Requests'), ('CONCURRENT_SESSIONS', 'Concurrent Sessions'), ('PASSWORD_COMPLEXITY', 'Password Complexity Score'), ('SESSION_DURATION', 'Session Duration'), ('API_REQUEST_FREQUENCY', 'API Request Frequency'), ('DATA_EXPORT_SIZE', 'Data Export Size'), ('FILE_UPLOAD_SIZE', 'File Upload Size'), ('LOG_RETENTION_DAYS', 'Log Retention Days')], max_length=30)),
                ('operator', models.CharField(choices=[('GREATER_THAN', '>'), ('GREATER_EQUAL', '>='), ('LESS_THAN', '<'), ('LESS_EQUAL', '<='), ('EQUAL', '='), ('NOT_EQUAL', '!=')], max_length=15)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (e.g., minutes, MB)', max_length=20)),
                ('scope', models.CharField(default='GLOBAL', help_text='Scope of threshold (GLOBAL, USER, IP, etc.)', max_length=50)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context for threshold application')),
                ('alert_enabled', models.BooleanField(default=True)),
                ('auto_block_enabled', models.BooleanField(default=False)),
                ('notification_recipients', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
