# Generated by Django 4.2.7 on 2025-12-31 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securitythreshold',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_security_thresholds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_security_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitypolicy',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modified_security_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='discovered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='related_events',
            field=models.ManyToManyField(blank=True, related_name='related_incidents', to='security.securityevent'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitydashboard',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitydashboard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_security_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='securitythreshold',
            index=models.Index(fields=['threshold_type'], name='security_se_thresho_91ce5c_idx'),
        ),
        migrations.AddIndex(
            model_name='securitythreshold',
            index=models.Index(fields=['is_active'], name='security_se_is_acti_f01731_idx'),
        ),
        migrations.AddIndex(
            model_name='securitypolicy',
            index=models.Index(fields=['policy_type'], name='security_se_policy__593fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='securitypolicy',
            index=models.Index(fields=['status'], name='security_se_status_81a8aa_idx'),
        ),
        migrations.AddIndex(
            model_name='securitypolicy',
            index=models.Index(fields=['valid_from'], name='security_se_valid_f_dedba1_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['incident_type'], name='security_se_inciden_ee2707_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['severity'], name='security_se_severit_2cdee4_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['status'], name='security_se_status_9d6acf_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['assigned_to'], name='security_se_assigne_58c527_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['case_number'], name='security_se_case_nu_6e5a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type'], name='security_se_event_t_e8f9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['severity'], name='security_se_severit_9bbb1c_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['status'], name='security_se_status_dedaae_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user'], name='security_se_user_id_74c3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['created_at'], name='security_se_created_841554_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['ip_address'], name='security_se_ip_addr_1ea45a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='security_au_action_089345_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type'], name='security_au_resourc_9b0ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='security_au_user_id_7ac444_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='security_au_timesta_82ac0d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address'], name='security_au_ip_addr_083b2c_idx'),
        ),
    ]
