# Generated by Django 4.2.7 on 2026-01-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_requester_alter_tickethistory_ticket'),
        ('tickets', '0004_ticket_assignment_status'),
    ]

    operations = [
    ]
