# Generated by Django 4.2.7 on 2026-02-11 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0007_ticketreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ticket Note',
                'verbose_name_plural': 'Ticket Notes',
                'db_table': 'ticket_notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='ticketreview',
            new_name='ticket_revi_ticket__815da8_idx',
            old_name='ticket_review_ticket_created',
        ),
        migrations.RenameIndex(
            model_name='ticketreview',
            new_name='ticket_revi_author__f1eca5_idx',
            old_name='ticket_review_author_created',
        ),
        migrations.AddField(
            model_name='ticketnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketnote',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='tickets.ticket'),
        ),
        migrations.AddIndex(
            model_name='ticketnote',
            index=models.Index(fields=['ticket', 'created_at'], name='ticket_note_ticket__fa3214_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketnote',
            index=models.Index(fields=['author', 'created_at'], name='ticket_note_author__e878c3_idx'),
        ),
    ]
